# Generated by Django 2.0.13 on 2019-05-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrinfo',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
